Importing the libraries

In [ ]:
import pandas as pd
import numpy as np

Data Preprocessing

In [ ]:
data=pd.read_csv("creditcard.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192217 entries, 0 to 192216
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    192217 non-null  float64
 1   V1      192217 non-null  float64
 2   V2      192217 non-null  float64
 3   V3      192217 non-null  float64
 4   V4      192216 non-null  float64
 5   V5      192216 non-null  float64
 6   V6      192216 non-null  float64
 7   V7      192216 non-null  float64
 8   V8      192216 non-null  float64
 9   V9      192216 non-null  float64
 10  V10     192216 non-null  float64
 11  V11     192216 non-null  float64
 12  V12     192216 non-null  float64
 13  V13     192216 non-null  float64
 14  V14     192216 non-null  float64
 15  V15     192216 non-null  float64
 16  V16     192216 non-null  float64
 17  V17     192216 non-null  float64
 18  V18     192216 non-null  float64
 19  V19     192216 non-null  float64
 20  V20     192216 non-null  float64
 21  V21     19

In [ ]:
y=data["Class"]

In [ ]:
class_counts = y.value_counts()

In [ ]:
print(class_counts)

0.0    191839
1.0       377
Name: Class, dtype: int64


In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
categorical_columns = data.select_dtypes(include=['object'])

In [ ]:
if not categorical_columns.empty:
    print("Categorical columns found:")
    print(categorical_columns.columns)
else:
    print("No categorical columns found.")

No categorical columns found.


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
col=data[['Amount']]

In [ ]:
col = sc.fit_transform(col)

In [ ]:
print(col)

[[ 0.24230716]
 [-0.34887214]
 [ 1.16385966]
 ...
 [-0.30614211]
 [-0.27942577]
 [ 0.06277663]]


In [ ]:
data=data.drop(['Amount'], axis=1)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 192216 entries, 0 to 192215
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    192216 non-null  float64
 1   V1      192216 non-null  float64
 2   V2      192216 non-null  float64
 3   V3      192216 non-null  float64
 4   V4      192216 non-null  float64
 5   V5      192216 non-null  float64
 6   V6      192216 non-null  float64
 7   V7      192216 non-null  float64
 8   V8      192216 non-null  float64
 9   V9      192216 non-null  float64
 10  V10     192216 non-null  float64
 11  V11     192216 non-null  float64
 12  V12     192216 non-null  float64
 13  V13     192216 non-null  float64
 14  V14     192216 non-null  float64
 15  V15     192216 non-null  float64
 16  V16     192216 non-null  float64
 17  V17     192216 non-null  float64
 18  V18     192216 non-null  float64
 19  V19     192216 non-null  float64
 20  V20     192216 non-null  float64
 21  V21     19

In [ ]:
data['amount']=col

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 192216 entries, 0 to 192215
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    192216 non-null  float64
 1   V1      192216 non-null  float64
 2   V2      192216 non-null  float64
 3   V3      192216 non-null  float64
 4   V4      192216 non-null  float64
 5   V5      192216 non-null  float64
 6   V6      192216 non-null  float64
 7   V7      192216 non-null  float64
 8   V8      192216 non-null  float64
 9   V9      192216 non-null  float64
 10  V10     192216 non-null  float64
 11  V11     192216 non-null  float64
 12  V12     192216 non-null  float64
 13  V13     192216 non-null  float64
 14  V14     192216 non-null  float64
 15  V15     192216 non-null  float64
 16  V16     192216 non-null  float64
 17  V17     192216 non-null  float64
 18  V18     192216 non-null  float64
 19  V19     192216 non-null  float64
 20  V20     192216 non-null  float64
 21  V21     19

In [ ]:
x=data.drop(['Class'], axis=1)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit([y])
[y] = imputer.transform([y])

Dealing with Unbalanced Data

In [ ]:
class_count_0, class_count_1 = data['Class'].value_counts()

class_0 = data[data['Class'] == 0]
class_1 = data[data['Class'] == 1]
print('class 0:', class_0.shape)
print('class 1:', class_1.shape)

class 0: (191839, 31)
class 1: (377, 31)


In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_smote, y_smote = smote.fit_resample(x, y)

In [ ]:
class_cnt=pd.Series(y_smote).value_counts()
print(class_cnt)

0.0    191839
1.0    191839
dtype: int64


Splitting the dataset into training and test set


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Training and testing the model with unbalanced data

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, f1_score, recall_score, precision_score
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix: \n", cm)
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("auroc: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test,y_pred))
print("recall score: ", recall_score(y_test,y_pred))
print("precision: ", precision_score(y_test,y_pred))

confusion matrix: 
 [[38370     3]
 [   16    55]]
accuracy score:  0.9995057746332328
auroc:  0.887284853676826
f1 score:  0.8527131782945736
recall score:  0.7746478873239436
precision:  0.9482758620689655


Training and testing the model after undersampling using SMOTE


In [ ]:
x_smote_train, x_smote_test, y_smote_train, y_smote_test = train_test_split(x_smote, y_smote, test_size = 0.2, random_state = 0)

In [ ]:
smote_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
smote_classifier.fit(x_smote_train, y_smote_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_smote_pred = smote_classifier.predict(x_smote_test)

In [ ]:
cm_smote= confusion_matrix(y_smote_test, y_smote_pred)
print("confusion matrix: \n", cm_smote)
print("accuracy score: ", accuracy_score(y_smote_test, y_smote_pred))
print("auroc: ", roc_auc_score(y_smote_test, y_smote_pred))
print("f1 score: ", f1_score(y_smote_test,y_smote_pred))
print("recall score: ", recall_score(y_smote_test,y_smote_pred))
print("precision: ", precision_score(y_smote_test,y_smote_pred))

confusion matrix: 
 [[38697    11]
 [    1 38027]]
accuracy score:  0.9998436196830692
auroc:  0.9998447623028708
f1 score:  0.9998422422632978
recall score:  0.9999737035868308
precision:  0.9997108155002892


In [ ]:
y_smote_pred_tr = smote_classifier.predict(x_smote_train)

cm_smote= confusion_matrix(y_smote_train, y_smote_pred_tr)
print("confusion matrix: \n", cm_smote)
print("accuracy score: ", accuracy_score(y_smote_train, y_smote_pred_tr))
print("auroc: ", roc_auc_score(y_smote_train, y_smote_pred_tr))
print("f1 score: ", f1_score(y_smote_train,y_smote_pred_tr))
print("recall score: ", recall_score(y_smote_train,y_smote_pred_tr))
print("precision: ", precision_score(y_smote_train,y_smote_pred_tr))

confusion matrix: 
 [[153131      0]
 [     0 153811]]
accuracy score:  1.0
auroc:  1.0
f1 score:  1.0
recall score:  1.0
precision:  1.0
